### ISSUE TITLE
Custom markers and squares

### ISSUE THREAD

**Issue by thewhisperinyourears** [shaack/cm-chessboard#147]
@shaack I am trying to add custom markers and board squares. Can I add that in my own css or do I have to edit the markers.css?

**Comment by shaack** [comment]
You can define the css where you want, if you load it in your page. See the Markers extension README: https://github.com/shaack/cm-chessboard/blob/master/src/extensions/markers/README.md 

Example:

```css
marker.marker-circle-red {
    stroke: #aa0000;
    stroke-width: 3px;
    opacity: 0.4;
}
```

For custom Markers, the SVG (slice id in the sprite) and the CSS (class) is needed. Where you define these, is your responsibility.

```
const myMarkerType = {class: "myMarkerCssClass", slice: "myMarkerIdInSvg"}
```
